name: release
on:
  push:
    branches:
      - master
#    tags:
#      - 'v*'  # 例如 v1.0.0
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          experimental: true

      - run: mise run package

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

