name: release
on:
  push:
    branches:
      - master
    tags:
#      - 'v*'
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          experimental: true

      - name: 测试命令1
        run: git rev-parse HEAD
      - name: 测试命令2
        run: |
          tags=($(git tag --merged $(git rev-parse HEAD) --sort=-creatordate))
          preTag=$(curl --silent "https://api.github.com/repos/huxiaoning/gitbook-helper/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")' || echo "")
          echo $tags

      - run: mise run package

      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: target/gitbook-helper-1.0-SNAPSHOT.jar

