name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          experimental: true

      - run: mise run package

      - name: prerelease
        run: |
          version=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          mv target/gitbook-helper-1.0-SNAPSHOT.jar gitbook-helper.jar
          sed "s|VERSION|$version|g" ./.github/release_template.md >> release.md

      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: gitbook-helper.jar
          body_path: './release.md'

