name: release
on:
  push:
    branches:
      - master
    tags:
#      - 'v*'
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          experimental: true

      - run: mise run release

      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: target/gitbook-helper-1.0-SNAPSHOT.jar

